version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./queueData:/var/lib/rabbitmq
    logging:
      driver: none
  consumer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.consumer
    depends_on:
      - rabbitmq
    restart: always
  producer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.producer
    depends_on:
      - rabbitmq
    restart: always
    